"""
CashPulse - Streamlit dashboard.

Works against either tier of this project:
  - local quickstart: SQLite at data/finance.db (default, no setup needed)
  - cloud edition: Postgres/RDS, picked up automatically when DATABASE_URL is set

This "same dashboard, config picks the backend" pattern is standard
12-factor practice, and it's also just convenient: you get one dashboard
to maintain instead of two.

For genuine practice with a real BI tool, also follow
dashboard/POWER_BI_TABLEAU_GUIDE.md (local tier) or cloud/README.md (cloud
tier) and connect Power BI or Tableau to the same database -- that's what
should end up on your resume as the "BI" line item, alongside this
dashboard as a code-based alternative. Power BI/Tableau are NOT wired up
automatically -- see that guide to connect one yourself. The toolbar's
data badge below runs a real COUNT(*) against the actual database on
every load, so the row count and "updated" timestamp are live, not
hardcoded -- proof this is real data, not a mock.

Styling note: this dashboard intentionally uses Streamlit's own default
layout and widgets (st.metric, st.container(border=True), st.success/
st.warning/st.info, native chart theming) instead of hand-rolled HTML/CSS.
The color scheme comes entirely from .streamlit/config.toml (dark base +
a green accent) -- one source of truth, so native Streamlit text always
matches its background instead of fighting a separately hardcoded palette.

Run:
    streamlit run dashboard/app.py                       # local SQLite
    DATABASE_URL=postgresql://... streamlit run dashboard/app.py   # cloud Postgres
"""

import os
import re
import subprocess
import sqlite3
import sys
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import streamlit_authenticator as stauth

LOCAL_DB_PATH = Path(__file__).parent.parent / "data" / "finance.db"
DATABASE_URL = os.environ.get("DATABASE_URL")
BACKEND = "postgres" if DATABASE_URL else "sqlite"


def _table_is_empty(db_path, table_name):
    conn = sqlite3.connect(db_path)
    try:
        return conn.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0] == 0
    finally:
        conn.close()


def _bootstrap_local_data():
    """First-run (and self-healing) setup for the local SQLite tier.

    data/finance.db and the CSVs it's built from are gitignored on purpose
    (they're generated artifacts, not source) -- which means a fresh clone,
    or a fresh deploy on something like Streamlit Community Cloud, starts
    with no database at all. Cloud deploy platforms only run
    `streamlit run dashboard/app.py`; there's no hook to run a setup script
    first. So: if the SQLite backend is selected and the database simply
    isn't there yet, run the full local pipeline once, automatically -- the
    same four steps the README asks you to run by hand locally (generate,
    load, detect anomalies, forecast). This is what makes "clone and run" or
    "open the deployed link" actually work with zero manual setup, instead
    of failing on a database that was never allowed into git to begin with.

    The ML backfill is checked separately from "does the db file exist,"
    not folded into the same guard -- Streamlit Community Cloud's redeploy
    on a git push pulls new code into the *same* running environment rather
    than starting from a truly fresh clone, so a database generated by an
    earlier deploy (before the ML steps were added here) sticks around
    across a code-only push. A single `if LOCAL_DB_PATH.exists(): return`
    would then skip the ML steps forever on that already-running deploy,
    even though the code now expects them -- which is exactly what happened
    the first time this shipped: the Anomalies and 30-Day Forecast sections
    silently rendered "nothing yet" in production even though the pipeline
    logic itself was fine. Checking the ML tables independently means this
    self-heals on the very next load, no manual reboot required.
    """
    repo_root = Path(__file__).parent.parent

    if not LOCAL_DB_PATH.exists():
        with st.spinner("First run: generating sample data..."):
            subprocess.run(
                [sys.executable, str(repo_root / "data" / "generate_data.py")],
                check=True, cwd=repo_root,
            )
            subprocess.run(
                [sys.executable, str(repo_root / "etl" / "load_to_db.py")],
                check=True, cwd=repo_root,
            )

    needs_ml = (
        _table_is_empty(LOCAL_DB_PATH, "ml_anomaly_flags")
        or _table_is_empty(LOCAL_DB_PATH, "ml_cashflow_forecast")
    )
    if needs_ml:
        with st.spinner("Running anomaly detection and cash-flow forecasting..."):
            subprocess.run(
                [sys.executable, str(repo_root / "ml" / "detect_anomalies.py")],
                check=True, cwd=repo_root,
            )
            subprocess.run(
                [sys.executable, str(repo_root / "ml" / "forecast_cashflow.py")],
                check=True, cwd=repo_root,
            )


# Set AWS_INTEGRATION_MODE=localstack when DATABASE_URL points at a *real*
# Postgres (Docker/local install) standing in for RDS, provisioned via
# Terraform against LocalStack instead of real AWS -- see
# cloud/terraform-localstack/ and INTEGRATION_PROOF_GUIDE.md. This exists
# so the Integrations section can say "practice mode" instead of
# incorrectly claiming a real AWS connection -- it never guesses.
AWS_INTEGRATION_MODE = os.environ.get("AWS_INTEGRATION_MODE", "").strip().lower()

# Where real integration proof lives once you've actually done the AWS /
# Power BI setup in INTEGRATION_PROOF_GUIDE.md -- the Integrations section
# below reads these paths live and only shows something if it's actually
# there, so it can never claim a connection that doesn't exist.
ASSETS_DIR = Path(__file__).parent / "assets" / "integration_proof"
POWERBI_URL_FILE = Path(__file__).parent / "assets" / "powerbi_report_url.txt"

def _require_login():
    """Gate the whole app behind a login before anything else renders.

    Uses streamlit-authenticator (bcrypt-hashed passwords + a signed cookie
    for session persistence across a page refresh, plus a logout button)
    rather than hand-rolling anything security-adjacent -- "don't roll your
    own auth" applies just as much to a portfolio project as a real one.

    The credentials in .streamlit/secrets.toml are deliberately checked
    into git and shown right on the login screen, which would be a real
    problem for an app protecting real accounts -- but there is nothing to
    protect here. Every login sees the same synthetic, seeded dataset
    `data/generate_data.py` produces, never anyone's real financial data.
    Publishing the demo logins is what keeps this a genuine "open the link
    and use it" portfolio piece instead of a private tool nobody but you
    can open -- the same reasoning as the rest of this project's honesty
    pattern (see the Integrations panel, and README's "Key design
    decisions").

    Returns (authenticator, username) once logged in; calls st.stop()
    first otherwise, so nothing after this call ever runs unauthenticated.
    """
    auth_cfg = st.secrets["auth"]
    authenticator = stauth.Authenticate(
        auth_cfg["credentials"].to_dict(),
        auth_cfg["cookie"]["name"],
        auth_cfg["cookie"]["key"],
        auth_cfg["cookie"]["expiry_days"],
    )
    authenticator.login(location="main")
    auth_status = st.session_state.get("authentication_status")

    if auth_status is False:
        st.error("Username or password is incorrect.")
        st.stop()
    if auth_status is not True:
        st.info(
            "**Demo credentials** -- this is a public portfolio demo running on "
            "synthetic data only, so these are meant to be used by anyone:\n\n"
            "- `demo` / `CashPulseDemo!26` -- sees all 5 demo accounts\n"
            "- `nina` / `NinaDemo!26` -- sees only Nina's personal account, to "
            "show the per-login access restriction actually working"
        )
        st.stop()

    # login() only calls st.rerun() itself when using a file-based config
    # (`path=`); with a plain dict (this app's setup, since credentials
    # live in st.secrets) it never does, so the same script run that just
    # processed the submitted form keeps going and renders the whole
    # dashboard *below* the still-drawn login form -- a jarring "both at
    # once" flash right after a successful login. Rerunning once, tracked
    # so it only fires the one time per login rather than looping, gives a
    # clean transition straight to the dashboard instead.
    if not st.session_state.get("_post_login_rerun_done"):
        st.session_state["_post_login_rerun_done"] = True
        st.rerun()

    return authenticator, st.session_state["username"]


st.set_page_config(page_title="CashPulse", page_icon="\U0001F4B0", layout="wide")

_authenticator, _username = _require_login()

if BACKEND == "sqlite":
    _bootstrap_local_data()

_engine = None
if BACKEND == "postgres":
    import sqlalchemy
    _engine = sqlalchemy.create_engine(DATABASE_URL, pool_pre_ping=True)

# ---------------------------------------------------------------------------
# Chart-only colors. Streamlit's native widgets (metrics, alerts, dataframes,
# text) all take their color from .streamlit/config.toml's [theme] block, so
# they're never hardcoded here and can't go out of sync with the app's actual
# background. Plotly figures are the one thing Streamlit's theme can't reach
# automatically, so they still need explicit colors -- kept to a small set,
# tuned for the dark theme + green accent in .streamlit/config.toml.
# ---------------------------------------------------------------------------
COLOR = {
    "good": "#22C55E",      # accent green -- positive / inflow / healthy
    "critical": "#F87171",  # soft red -- negative / outflow / at-risk
    "warning": "#FBBF24",   # amber -- simulated / caution status
    "muted": "#8B95A5",     # axis labels, secondary chart text
    "grid": "#2A2F3A",      # gridlines against the dark chart background
    "text": "#E5E7EB",      # primary chart text (labels, hover)
}

# Sequential ramp (muted -> bright green) for magnitude encoding on the
# category-spend chart. Brightest = highest spend, since a brighter mark
# reads as "most prominent" against a dark surface.
SEQUENTIAL_GREEN = ["#14532D", "#15803D", "#16A34A", "#22C55E", "#4ADE80", "#86EFAC"]

FONT_STACK = 'system-ui, -apple-system, "Segoe UI", sans-serif'

# Same logical queries, two physical shapes -- sqlite tables are flat
# (v_account_health, ml_anomaly_flags, ...); the cloud tier reads dbt's
# analytics.* marts and the ml.* tables the cloud ML scripts write to.
QUERIES = {
    "sqlite": {
        "accounts": "SELECT account_id, account_name, account_type FROM accounts",
        "health": "SELECT * FROM v_account_health WHERE account_id = :account_id",
        "monthly": "SELECT * FROM v_monthly_cashflow WHERE account_id = :account_id ORDER BY month",
        "forecast": "SELECT * FROM ml_cashflow_forecast WHERE account_id = :account_id ORDER BY forecast_date",
        "category_spend": "SELECT * FROM v_category_spend_monthly WHERE account_id = :account_id ORDER BY month DESC",
        "anomalies": """
            SELECT f.anomaly_score, f.reason, t.txn_date, t.amount, c.category_name
            FROM ml_anomaly_flags f
            JOIN transactions t ON t.transaction_id = f.transaction_id
            JOIN categories c ON c.category_id = t.category_id
            WHERE t.account_id = :account_id
            ORDER BY f.anomaly_score DESC
        """,
        "txn_count": "SELECT COUNT(*) AS n FROM transactions",
        "budget_vs_actual": """
            SELECT
                b.month,
                c.category_name,
                b.budgeted_amount,
                COALESCE((
                    SELECT SUM(t.amount)
                    FROM transactions t
                    WHERE t.account_id = b.account_id
                      AND t.category_id = b.category_id
                      AND t.txn_type = 'debit'
                      AND strftime('%Y-%m', t.txn_date) = b.month
                ), 0) AS actual_amount
            FROM budgets b
            JOIN categories c ON c.category_id = b.category_id
            WHERE b.account_id = :account_id
            ORDER BY b.month DESC, c.category_name
        """,
        "recurring": """
            SELECT
                m.merchant_name,
                COUNT(*) AS occurrence_count,
                ROUND(AVG(t.amount), 2) AS typical_amount,
                MAX(t.txn_date) AS last_txn_date,
                (
                    SELECT t2.amount FROM transactions t2
                    WHERE t2.account_id = t.account_id
                      AND t2.merchant_id = t.merchant_id
                      AND t2.is_recurring = 1
                    ORDER BY t2.txn_date DESC LIMIT 1
                ) AS last_amount
            FROM transactions t
            JOIN merchants m ON m.merchant_id = t.merchant_id
            WHERE t.account_id = :account_id AND t.is_recurring = 1
            GROUP BY t.merchant_id, m.merchant_name
            ORDER BY last_txn_date DESC
        """,
        "category_transactions": """
            SELECT t.txn_date, m.merchant_name, t.amount, t.is_recurring
            FROM transactions t
            JOIN categories c ON c.category_id = t.category_id
            LEFT JOIN merchants m ON m.merchant_id = t.merchant_id
            WHERE t.account_id = :account_id
              AND c.category_name = :category_name
              AND t.txn_type = 'debit'
              AND strftime('%Y-%m', t.txn_date) BETWEEN :start_month AND :end_month
            ORDER BY t.txn_date DESC
        """,
        # The next three back the "Manage Transactions" section, which only
        # exists for this tier -- see _get_write_conn()'s docstring for why.
        "categories": "SELECT category_id, category_name FROM categories ORDER BY category_name",
        "merchants": "SELECT merchant_id, merchant_name, default_category_id FROM merchants ORDER BY merchant_name",
        "all_transactions": """
            SELECT t.transaction_id, t.txn_date, m.merchant_name, c.category_name,
                   t.amount, t.txn_type, t.description, t.is_recurring
            FROM transactions t
            JOIN categories c ON c.category_id = t.category_id
            LEFT JOIN merchants m ON m.merchant_id = t.merchant_id
            WHERE t.account_id = :account_id
            ORDER BY t.txn_date DESC, t.transaction_id DESC
            LIMIT 300
        """,
    },
    "postgres": {
        "accounts": "SELECT account_id, account_name, account_type FROM analytics.dim_accounts",
        "health": "SELECT * FROM analytics.account_health WHERE account_id = :account_id",
        "monthly": "SELECT * FROM analytics.monthly_cashflow WHERE account_id = :account_id ORDER BY month",
        "forecast": "SELECT * FROM ml.cashflow_forecast WHERE account_id = :account_id ORDER BY forecast_date",
        "category_spend": "SELECT * FROM analytics.category_spend_monthly WHERE account_id = :account_id ORDER BY month DESC",
        "anomalies": """
            SELECT f.anomaly_score, f.reason, t.txn_date, t.amount, t.category_name
            FROM ml.anomaly_flags f
            JOIN analytics.fct_transactions t ON t.transaction_id = f.transaction_id
            WHERE t.account_id = :account_id
            ORDER BY f.anomaly_score DESC
        """,
        "txn_count": "SELECT COUNT(*) AS n FROM analytics.fct_transactions",
        "budget_vs_actual": """
            SELECT month, category_name, budgeted_amount, actual_amount
            FROM analytics.budget_vs_actual
            WHERE account_id = :account_id
            ORDER BY month DESC, category_name
        """,
        "recurring": """
            SELECT merchant_name, occurrence_count, typical_amount, last_txn_date, last_amount
            FROM analytics.recurring_transactions
            WHERE account_id = :account_id
            ORDER BY last_txn_date DESC
        """,
        "category_transactions": """
            SELECT txn_date, merchant_name, amount, is_recurring
            FROM analytics.fct_transactions
            WHERE account_id = :account_id
              AND category_name = :category_name
              AND txn_type = 'debit'
              AND to_char(txn_date, 'YYYY-MM') BETWEEN :start_month AND :end_month
            ORDER BY txn_date DESC
        """,
    },
}


@st.cache_data(ttl=60)
def load_table(query_key, params=None):
    query = QUERIES[BACKEND][query_key]
    params = params or {}
    if BACKEND == "postgres":
        return pd.read_sql_query(sqlalchemy.text(query), _engine, params=params)
    conn = sqlite3.connect(LOCAL_DB_PATH)
    try:
        return pd.read_sql_query(query, conn, params=params)
    finally:
        conn.close()


def _get_write_conn():
    """A separate, non-cached connection for the "Manage Transactions"
    write path -- SQLite tier only.

    `load_table` above is deliberately read-only and cached (`ttl=60`);
    routing writes through here instead, then explicitly clearing that
    cache and rerunning, keeps the read path simple while still making
    edits show up immediately everywhere else on the page. This only
    exists for SQLite: the cloud tier's dbt pipeline treats `raw.*` as
    immutable and rebuilds `analytics.*` from it on every run, so a direct
    write to Postgres here would just get silently overwritten on the next
    `dbt run` -- manual entry stays local-tier-only until that's addressed
    (see ROADMAP.md)."""
    return sqlite3.connect(LOCAL_DB_PATH, timeout=10)


def _get_or_create_merchant(conn, merchant_name, category_id):
    """Look up a merchant by name, or create it with `category_id` as its
    default -- this is the "inline learning" half of auto-categorization:
    the first time a brand-new merchant is used, whatever category you
    pick for it becomes its suggested category from then on."""
    row = conn.execute(
        "SELECT merchant_id FROM merchants WHERE merchant_name = ?", (merchant_name,)
    ).fetchone()
    if row:
        return row[0]
    cur = conn.execute(
        "INSERT INTO merchants (merchant_name, default_category_id) VALUES (?, ?)",
        (merchant_name, category_id),
    )
    return cur.lastrowid


def _clean_text(value):
    """Coerce a data_editor / form cell to None if it's NaN or blank, since
    a blank optional text field round-trips through pandas as NaN, and
    `NaN or None` evaluates to NaN (NaN is truthy), not None."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return None
    text = str(value).strip()
    return text or None


def _invalidate_and_rerun():
    """After any write: drop the cached reads and rerun, same as the
    toolbar's own "Refresh data" button, so the change is visible
    everywhere on the page immediately instead of waiting up to 60s for
    the cache to expire on its own."""
    load_table.clear()
    get_data_status.clear()
    st.rerun()


def backend_ready():
    if BACKEND == "sqlite":
        return LOCAL_DB_PATH.exists()
    try:
        with _engine.connect() as conn:
            conn.exec_driver_sql("SELECT 1")
        return True
    except Exception as e:
        st.session_state["_connection_error"] = str(e)
        return False


@st.cache_data(ttl=60)
def get_data_status():
    """Live proof-of-life for the data badge: an actual COUNT(*) run
    against whichever backend is configured, plus a real last-modified
    signal -- never a hardcoded number."""
    txn_count = int(load_table("txn_count")["n"].iloc[0])
    if BACKEND == "sqlite":
        mtime = datetime.fromtimestamp(LOCAL_DB_PATH.stat().st_mtime)
        freshness = f"data file updated {mtime.strftime('%b %d, %Y %I:%M %p')}"
        source_label = "SQLite (local file)"
    else:
        freshness = "live connection, queried just now"
        source_label = "Postgres (cloud RDS)"
    return source_label, txn_count, freshness


def base_layout(fig, height=340):
    """Shared, undecorated chart chrome: transparent surface (so the chart
    blends into whatever Streamlit theme surface sits behind it), recessive
    gridlines, brand font. Transparent backgrounds mean this never needs to
    know the exact theme color -- it just matches automatically."""
    fig.update_layout(
        height=height,
        margin=dict(l=10, r=10, t=10, b=10),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(family=FONT_STACK, color=COLOR["text"], size=13),
        xaxis=dict(showgrid=False, linecolor=COLOR["grid"], color=COLOR["muted"]),
        yaxis=dict(showgrid=True, gridcolor=COLOR["grid"], zeroline=True,
                    zerolinecolor=COLOR["grid"], color=COLOR["muted"]),
    )
    return fig


def _slug(text):
    """Filesystem/URL-safe filename fragment, e.g. "Nina's Checking" -> "ninas_checking"."""
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")


def _compute_recommendations(category_spend, budget_vs_actual, current_balance, avg_daily_burn,
                              forecast, cut_pct):
    """Rules-based "what if" recommendations -- deliberately NOT a model.

    Every number here is plain arithmetic pulled from the same tables that
    already back the KPI row, the category chart, and the budget chart
    above, so a skeptical reader can check the math themselves rather than
    trust a black box. This is the honest way to do "prescriptive": no
    hidden model, no training data, no claim of predicting behavior -- just
    "if X changed, here is exactly what that does to your numbers."

    Two kinds of recommendation, ranked over-budget-first:
      1. A category already over budget this month. The recommendation is
         "get back to budget," and the savings is the actual overage --
         a fact already sitting in the data, not a guess.
      2. The largest discretionary/variable-expense categories that are
         NOT already over budget. The recommendation is a hypothetical cut
         of `cut_pct`% (a slider in the UI) -- this one genuinely is a
         what-if, and is labeled as such.

    Each recommendation is translated into two consequences a person can
    act on: the change to this account's runway (same avg_daily_burn as
    the KPI row) and the shift in the 30-day forecasted ending balance
    (same series as the forecast chart above).
    """
    if category_spend.empty:
        return []

    latest_month = category_spend["month"].max()
    latest_spend = category_spend[category_spend["month"] == latest_month]

    recs = []
    seen_categories = set()

    if not budget_vs_actual.empty:
        bva_latest = budget_vs_actual[budget_vs_actual["month"] == latest_month].copy()
        bva_latest["overage"] = bva_latest["actual_amount"] - bva_latest["budgeted_amount"]
        over = bva_latest[bva_latest["overage"] > 0].sort_values("overage", ascending=False)
        for _, row in over.iterrows():
            recs.append({
                "category": row["category_name"],
                "headline": (f"\U0001F534 {row['category_name']} is ${row['overage']:,.0f} over its "
                             f"${row['budgeted_amount']:,.0f} budget this month "
                             f"(${row['actual_amount']:,.0f} spent)."),
                "action": "Get back to budget",
                "monthly_savings": float(row["overage"]),
            })
            seen_categories.add(row["category_name"])

    discretionary = latest_spend[
        latest_spend["category_group"].isin(["discretionary", "variable_expense"])
        & ~latest_spend["category_name"].isin(seen_categories)
    ].sort_values("total_amount", ascending=False)
    for _, row in discretionary.iterrows():
        savings = float(row["total_amount"]) * (cut_pct / 100.0)
        if savings <= 0:
            continue
        recs.append({
            "category": row["category_name"],
            "headline": (f"\U0001F4A1 {row['category_name']} is your top discretionary/variable "
                         f"spend this month at ${row['total_amount']:,.0f}."),
            "action": f"Hypothetical: cut it by {cut_pct}%",
            "monthly_savings": savings,
        })
        seen_categories.add(row["category_name"])

    latest_forecast_balance = float(forecast["predicted_balance"].iloc[-1]) if not forecast.empty else None

    for rec in recs:
        monthly_savings = rec["monthly_savings"]
        daily_savings = monthly_savings / 30.0
        # "Runway" (balance / burn) only means something for a positive
        # balance -- for a negative one, dividing by a *smaller* burn rate
        # after the hypothetical cut makes the ratio a *bigger* negative
        # number, which would read as "spending less makes it worse." That's
        # a real degenerate case of the ratio, not a bug, but it's the kind
        # of thing an attentive reviewer would flag, so it's suppressed here
        # rather than shown as a confusing negative-days delta.
        if avg_daily_burn > 0 and current_balance > 0:
            old_runway = current_balance / avg_daily_burn
            new_burn = max(avg_daily_burn - daily_savings, 0.0)
            new_runway = (current_balance / new_burn) if new_burn > 0 else float("inf")
            rec["old_runway"], rec["new_runway"] = old_runway, new_runway
            rec["runway_na_reason"] = None
        else:
            rec["old_runway"] = rec["new_runway"] = None
            rec["runway_na_reason"] = (
                "not meaningful with a negative balance" if current_balance <= 0 else "no burn detected"
            )
        if latest_forecast_balance is not None:
            rec["old_forecast_balance"] = latest_forecast_balance
            rec["new_forecast_balance"] = latest_forecast_balance + monthly_savings
        else:
            rec["old_forecast_balance"] = rec["new_forecast_balance"] = None

    # Capped at 3 so this reads as "here's what to actually do," not
    # another wall of data -- the same reasoning as the CSV export button
    # for anomalies: surface the highest-signal items, not everything.
    return recs[:3]


def _redact_db_host(url):
    """Show which host we're actually querying without leaking credentials
    -- used only for a status label, never logged or sent anywhere."""
    try:
        parsed = urlparse(url)
        return parsed.hostname or "unknown host"
    except Exception:
        return "unknown host"


def render_integrations():
    """Real integration status, read live from the environment and from
    files you drop in yourself after wiring up real AWS/Power BI (see the
    README's "Connecting real AWS & BI tools" section) -- there is no
    hardcoded "connected" state here. If you haven't done that setup yet,
    this honestly says so instead of faking it."""
    st.subheader("Integrations & Proof")

    aws_col, bi_col = st.columns(2)

    with aws_col, st.container(border=True):
        st.markdown("**AWS Cloud Infrastructure**")
        if BACKEND == "postgres" and AWS_INTEGRATION_MODE == "localstack":
            host = _redact_db_host(DATABASE_URL)
            st.warning(f"\U0001F9EA Simulated · LocalStack + local Postgres at `{host}`")
            st.caption("Practice mode, not real AWS: Terraform provisioned S3 against "
                       "LocalStack (a free, no-account AWS simulator), and this Postgres "
                       "is running locally/in Docker as a stand-in for RDS -- no AWS "
                       "account or card was used.")
        elif BACKEND == "postgres":
            host = _redact_db_host(DATABASE_URL)
            st.success(f"Connected · querying RDS Postgres at `{host}`")
            st.caption("This dashboard is reading live data from AWS RDS right now, "
                       "not a local file -- the DATABASE_URL environment variable is set.")
        else:
            st.info("Not connected yet · reading local SQLite")
            st.caption("Provision real AWS via `cloud/terraform`, or the free no-account "
                       "path via `cloud/terraform-localstack` -- either flips this "
                       "automatically once DATABASE_URL is set. See the README's "
                       "\"Connecting real AWS & BI tools\" section.")
        aws_screenshot = ASSETS_DIR / "aws_rds.png"
        if aws_screenshot.exists():
            caption = ("LocalStack + local Postgres -- terraform apply / awslocal output"
                       if AWS_INTEGRATION_MODE == "localstack" else
                       "AWS RDS console -- instance status")
            st.image(str(aws_screenshot), caption=caption, width="stretch")

    with bi_col, st.container(border=True):
        st.markdown("**Power BI / Tableau**")
        report_url = None
        if POWERBI_URL_FILE.exists():
            report_url = POWERBI_URL_FILE.read_text().strip() or None
        if report_url:
            st.success("Published")
            st.link_button("View live Power BI report ↗", report_url)
        else:
            st.info("Not connected yet")
            st.caption("Connect Power BI or Tableau to this database and publish a report, "
                       "then save the link in dashboard/assets/powerbi_report_url.txt to "
                       "show it here automatically -- see the README's \"Connecting real "
                       "AWS & BI tools\" section.")
        bi_screenshot = ASSETS_DIR / "powerbi_report.png"
        if bi_screenshot.exists():
            st.image(str(bi_screenshot), caption="Power BI report -- model & visuals", width="stretch")


def main():
    with st.sidebar:
        st.caption(f"Logged in as **{st.session_state.get('name', _username)}**")
        _authenticator.logout("Log out", "sidebar")
        # logout() doesn't rerun on its own, so without this, the rest of
        # this page keeps rendering with stale (now-invalid) auth state for
        # one more pass before the login gate reappears on the next
        # interaction. Rerunning immediately makes "Log out" feel instant.
        if not st.session_state.get("authentication_status"):
            st.session_state.pop("_post_login_rerun_done", None)
            st.rerun()

    st.title("\U0001F4B0 CashPulse")
    st.caption("Personal & SME finance health monitor")

    if not backend_ready():
        if BACKEND == "sqlite":
            st.error("No database found. Run `python data/generate_data.py` then "
                      "`python etl/load_to_db.py` first.")
        else:
            st.error("Could not connect to Postgres via DATABASE_URL. Run "
                      "`python cloud/pipeline/run_pipeline.py` first, and check "
                      f"cloud/.env. Error: {st.session_state.get('_connection_error')}")
        return

    accounts = load_table("accounts")

    # Restrict which accounts this login can see. "*" means full access
    # (the "demo" login); anything else is an exact list of account names --
    # this is what makes "Authentication" in the roadmap mean more than
    # just a locked door: different logins genuinely see different data,
    # the way real multi-tenant access control would.
    allowed = st.secrets["auth"]["account_access"].get(_username, [])
    if "*" not in allowed:
        accounts = accounts[accounts["account_name"].isin(allowed)]
    if accounts.empty:
        st.error(f"No accounts are configured for **{_username}** in "
                  "`st.secrets['auth']['account_access']`. Contact whoever set up this deploy.")
        st.stop()

    source_label, txn_count, freshness = get_data_status()

    # --- Toolbar: account picker + live data badge -----------------------
    with st.container(border=True):
        tb1, tb2, tb3 = st.columns([2, 1, 3])
        with tb1:
            account_name = st.selectbox("Account", accounts["account_name"])
        with tb2:
            st.write("")
            if st.button("↻ Refresh data"):
                load_table.clear()
                get_data_status.clear()
                st.rerun()
        with tb3:
            st.write("")
            st.caption(f"🟢 **{source_label}** · **{txn_count:,}** real transactions loaded "
                       f"· {freshness}")

    account_id = int(accounts.loc[accounts["account_name"] == account_name, "account_id"].iloc[0])

    health = load_table("health", {"account_id": account_id})
    monthly = load_table("monthly", {"account_id": account_id})
    forecast = load_table("forecast", {"account_id": account_id})
    category_spend = load_table("category_spend", {"account_id": account_id})
    anomalies = load_table("anomalies", {"account_id": account_id})
    budget_vs_actual = load_table("budget_vs_actual", {"account_id": account_id})
    recurring = load_table("recurring", {"account_id": account_id})

    # --- KPI row -----------------------------------------------------------
    current_balance = float(health["current_balance"].iloc[0]) if not health.empty else 0.0
    avg_daily_burn = float(health["avg_daily_burn"].iloc[0]) if not health.empty else 0.0
    runway_days = (current_balance / avg_daily_burn) if avg_daily_burn > 0 else float("inf")
    last_month_net = float(monthly["net_flow"].iloc[-1]) if not monthly.empty else 0.0

    if runway_days == float("inf"):
        runway_text, runway_delta, runway_color = "∞", "no burn detected", "normal"
    elif runway_days < 60:
        runway_text, runway_delta, runway_color = f"{runway_days:,.0f} days", "below 60-day buffer", "inverse"
    else:
        runway_text, runway_delta, runway_color = f"{runway_days:,.0f} days", "healthy buffer", "normal"

    net_flow_delta = "inflow" if last_month_net >= 0 else "outflow"
    net_flow_color = "normal" if last_month_net >= 0 else "inverse"

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Current Balance", f"${current_balance:,.0f}")
    col2.metric("Avg Daily Burn (30d)", f"${avg_daily_burn:,.0f}")
    col3.metric("Runway", runway_text, delta=runway_delta, delta_color=runway_color)
    col4.metric("Last Month Net Flow", f"${last_month_net:,.0f}", delta=net_flow_delta, delta_color=net_flow_color)

    if runway_days < 60:
        st.warning(f"⚠️ At the current burn rate, this account has an estimated "
                    f"{runway_days:,.0f}-day runway. Consider reviewing discretionary spend below.")

    # --- Prescriptive recommendations ---------------------------------------
    # The roadmap's own framing: move from descriptive ("here's an anomaly")
    # to prescriptive ("cutting dining spend by 15% gets your runway back
    # over 90 days"). Deliberately not an ML model -- see
    # _compute_recommendations' docstring for why a transparent rules engine
    # is the more defensible choice here. Uses the latest month regardless
    # of the date-range picker below, same as the KPI row above: this is a
    # "what should I do right now" panel, not something you'd browse
    # historically.
    st.subheader("\U0001F4A1 Prescriptive Recommendations")
    with st.container(border=True):
        cut_pct = st.slider(
            "Hypothetical cut applied to top discretionary/variable categories "
            "not already over budget",
            min_value=5, max_value=30, value=15, step=5, key="rec_cut_pct",
        )
        recommendations = _compute_recommendations(
            category_spend, budget_vs_actual, current_balance, avg_daily_burn, forecast, cut_pct,
        )
        if not recommendations:
            st.info("Nothing stands out this month -- no budgets exceeded and no notable "
                     "discretionary/variable spend to trim.")
        else:
            for i, rec in enumerate(recommendations):
                st.markdown(f"**{rec['headline']}**")
                st.caption(f"{rec['action']} → frees up ~${rec['monthly_savings']:,.0f}/month")
                m1, m2, m3 = st.columns(3)
                m1.metric("Monthly savings", f"${rec['monthly_savings']:,.0f}")
                if rec["old_runway"] is not None:
                    old_txt = "∞" if rec["old_runway"] == float("inf") else f"{rec['old_runway']:,.0f}d"
                    new_txt = "∞" if rec["new_runway"] == float("inf") else f"{rec['new_runway']:,.0f}d"
                    if rec["new_runway"] == float("inf"):
                        delta_txt = "no longer burning cash"
                    else:
                        diff_days = round(rec["new_runway"] - rec["old_runway"])
                        # round() can produce -0 for a negligible negative
                        # diff (e.g. a $5 cut against a huge burn rate);
                        # "-0" reads as a display bug, so normalize it.
                        delta_txt = "no meaningful change" if diff_days == 0 else f"{diff_days:+,} days"
                    m2.metric("Runway", f"{old_txt} → {new_txt}", delta=delta_txt)
                else:
                    m2.metric("Runway", "n/a", delta=rec["runway_na_reason"])
                if rec["old_forecast_balance"] is not None:
                    m3.metric(
                        "30-day forecasted balance",
                        f"${rec['new_forecast_balance']:,.0f}",
                        delta=f"+${rec['monthly_savings']:,.0f} vs ${rec['old_forecast_balance']:,.0f} shown above",
                    )
                else:
                    m3.metric("30-day forecasted balance", "n/a", delta="no forecast yet")
                if i < len(recommendations) - 1:
                    st.divider()
        st.caption("Rules-based, not a model: every number above is plain arithmetic from the "
                    "same tables behind the KPIs, the category chart, and the forecast, so you "
                    "can check the math yourself. Over-budget rows use the actual overage; "
                    "everything else uses the hypothetical cut % set above.")

    # --- Cash flow trend + forecast ---------------------------------------
    # These used to share one chart (monthly bars + daily forecast line on a
    # second y-axis). Two problems with that: the bars are monthly and the
    # forecast is daily, so 30 daily points get squeezed into a sliver a few
    # pixels wide at the end of an 18-month axis -- any real day-to-day
    # movement in the forecast then reads as a jagged spike. And the two
    # series don't even share units (net flow vs. balance), so the shared
    # axis was misleading on top of being cramped. Split into two charts,
    # each on its own axis and its own time scale, instead.
    st.subheader("Cash Flow: History & 30-Day Forecast")
    hist_col, forecast_col = st.columns(2)

    with hist_col, st.container(border=True):
        st.caption("Historical Net Flow (monthly)")
        if not monthly.empty:
            # Net flow sign means good/bad, so it uses the fixed status
            # colors (good/critical) rather than an ad hoc categorical
            # color -- paired with a two-item legend so color never
            # carries the meaning alone.
            bar_colors = [COLOR["critical"] if v < 0 else COLOR["good"] for v in monthly["net_flow"]]
            fig_hist = go.Figure()
            fig_hist.add_trace(go.Bar(
                x=monthly["month"], y=monthly["net_flow"], marker_color=bar_colors,
                showlegend=False, hovertemplate="%{x}<br>$%{y:,.0f}<extra></extra>",
            ))
            # Two invisible marker traces purely to carry the icon+label
            # legend for the status colors used above.
            fig_hist.add_trace(go.Bar(x=[None], y=[None], marker_color=COLOR["good"], name="▲ Inflow (net positive)"))
            fig_hist.add_trace(go.Bar(x=[None], y=[None], marker_color=COLOR["critical"], name="▼ Outflow (net negative)"))
            fig_hist.update_layout(
                xaxis_title="", yaxis_title="Net Flow ($)",
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0, font=dict(size=11)),
                bargap=0.25,
            )
            base_layout(fig_hist)
            st.plotly_chart(fig_hist, use_container_width=True, config={"displayModeBar": False})
        else:
            st.info("No historical data yet.")

    with forecast_col, st.container(border=True):
        st.caption("30-Day Balance Forecast (daily)")
        if not forecast.empty:
            fig_fc = go.Figure()
            fig_fc.add_trace(go.Scatter(
                x=forecast["forecast_date"], y=forecast["predicted_balance"],
                name="Forecasted Balance", mode="lines+markers",
                line=dict(color=COLOR["good"], width=2.5),
                marker=dict(size=6, color=COLOR["good"]),
                fill="tozeroy", fillcolor="rgba(34, 197, 94, 0.12)",
                hovertemplate="%{x}<br>$%{y:,.0f}<extra></extra>",
            ))
            fig_fc.add_hline(y=current_balance, line_dash="dot", line_color=COLOR["muted"],
                              annotation_text="Current balance", annotation_position="bottom right",
                              annotation_font_color=COLOR["muted"])
            fig_fc.update_layout(xaxis_title="", yaxis_title="Forecasted Balance ($)", showlegend=False)
            base_layout(fig_fc)
            st.plotly_chart(fig_fc, use_container_width=True, config={"displayModeBar": False})
        else:
            st.info("No forecast data yet.")

    # --- Date range filter ---------------------------------------------------
    # Feeds the two sections below (Spend by Category, Budget vs. Actual),
    # which used to be locked to whatever "latest month" happened to be in
    # the data -- no way to look at a different month or a wider window.
    # Defaults to the latest available month so the page looks the same as
    # before until you touch it. The KPI row above (avg daily burn, runway)
    # deliberately stays a fixed "as of today" snapshot rather than
    # following this filter -- those are current-status numbers, not a
    # report you'd browse historically.
    if not monthly.empty:
        min_month_date = datetime.strptime(monthly["month"].min(), "%Y-%m").date()
        max_month_date = datetime.strptime(monthly["month"].max(), "%Y-%m").date()
        date_range = st.date_input(
            "Date range (filters Spend by Category and Budget vs. Actual below)",
            value=(max_month_date, max_month_date),
            min_value=min_month_date, max_value=max_month_date,
        )
        if isinstance(date_range, (tuple, list)) and len(date_range) == 2:
            range_start, range_end = date_range
        else:
            single = date_range[0] if isinstance(date_range, (tuple, list)) else date_range
            range_start = range_end = single
        if range_start > range_end:
            range_start, range_end = range_end, range_start
        start_month = range_start.strftime("%Y-%m")
        end_month = range_end.strftime("%Y-%m")
    else:
        start_month, end_month = "0000-00", "9999-99"
    range_label = start_month if start_month == end_month else f"{start_month} → {end_month}"

    category_spend_filtered = category_spend[
        (category_spend["month"] >= start_month) & (category_spend["month"] <= end_month)
    ]
    budget_vs_actual_filtered = budget_vs_actual[
        (budget_vs_actual["month"] >= start_month) & (budget_vs_actual["month"] <= end_month)
    ]

    # --- Category breakdown ------------------------------------------------
    # A pie chart doesn't hold up once there are more than a handful of
    # categories (this data has up to ~14): slice angles get too thin to
    # compare and color would have to carry pure identity across too many
    # slots. This is really a magnitude-comparison job ("which categories
    # cost the most"), so it becomes a single-hue horizontal bar ranked by
    # spend, with the $ amount labeled directly on each bar.
    st.subheader("Spend by Category")
    with st.container(border=True):
        st.caption(f"Showing: {range_label} · click a bar to see its transactions")
        if not category_spend_filtered.empty:
            latest = (
                category_spend_filtered.groupby("category_name", as_index=False)["total_amount"].sum()
            )
            latest = latest.sort_values("total_amount", ascending=True)

            n = len(latest)
            if n > 1:
                ramp_idx = [round(i * (len(SEQUENTIAL_GREEN) - 1) / (n - 1)) for i in range(n)]
            else:
                ramp_idx = [len(SEQUENTIAL_GREEN) - 1]
            bar_colors = [SEQUENTIAL_GREEN[i] for i in ramp_idx]

            max_spend = float(latest["total_amount"].max())

            fig_cat = go.Figure()
            fig_cat.add_trace(go.Bar(
                x=latest["total_amount"], y=latest["category_name"], orientation="h",
                marker_color=bar_colors,
                text=[f"${v:,.0f}" for v in latest["total_amount"]],
                textposition="outside", textfont=dict(color=COLOR["text"], size=12),
                cliponaxis=False,
                hovertemplate="%{y}<br>$%{x:,.0f}<extra></extra>",
            ))
            fig_cat.update_layout(
                xaxis_title="Total Spend ($)", yaxis_title="",
                showlegend=False, bargap=0.3,
            )
            # Headroom past the longest bar so its outside label isn't
            # clipped by the plot edge, and a right margin sized the same way.
            fig_cat.update_xaxes(showgrid=True, range=[0, max_spend * 1.22])
            base_layout(fig_cat, height=max(300, 34 * n))
            fig_cat.update_layout(margin=dict(l=10, r=30, t=10, b=10))
            # on_select="rerun" turns a bar click into a normal Streamlit
            # rerun with the clicked point available below -- no custom JS
            # needed, just Streamlit's native chart-selection event (1.35+).
            cat_event = st.plotly_chart(
                fig_cat, use_container_width=True, config={"displayModeBar": False},
                on_select="rerun", selection_mode="points", key="category_chart",
            )

            selected_category = None
            if cat_event and cat_event["selection"]["points"]:
                selected_category = cat_event["selection"]["points"][0].get("y")

            if selected_category:
                drill = load_table("category_transactions", {
                    "account_id": account_id, "category_name": selected_category,
                    "start_month": start_month, "end_month": end_month,
                })
                st.markdown(f"**{selected_category} transactions — {range_label}**")
                if not drill.empty:
                    st.dataframe(
                        drill.rename(columns={
                            "txn_date": "Date", "merchant_name": "Merchant",
                            "amount": "Amount", "is_recurring": "Recurring",
                        }).style.format({"Amount": "${:,.2f}"}),
                        width="stretch",
                    )
                else:
                    st.info("No transactions found for this category in the selected range.")
        else:
            st.info("No category spend data for the selected date range.")

    # --- Budget vs. actual ---------------------------------------------------
    # Status (over/under budget) is what matters here, not raw category
    # identity, so "Actual" is split into two same-hued-family traces (good/
    # critical) rather than one trace colored per-bar -- a single bar trace
    # can't carry two different legend colors cleanly, and color needs to
    # follow a fixed entity (the status), never vary within one legend swatch.
    st.subheader("Budget vs. Actual")
    with st.container(border=True):
        st.caption(f"Showing: {range_label}")
        if not budget_vs_actual_filtered.empty:
            bva = (
                budget_vs_actual_filtered
                .groupby("category_name", as_index=False)[["budgeted_amount", "actual_amount"]]
                .sum()
            )
            bva = bva.sort_values("budgeted_amount", ascending=True)
            within = bva[bva["actual_amount"] <= bva["budgeted_amount"]]
            over = bva[bva["actual_amount"] > bva["budgeted_amount"]]

            fig_bva = go.Figure()
            fig_bva.add_trace(go.Bar(
                x=bva["budgeted_amount"], y=bva["category_name"], orientation="h",
                name="Budgeted", marker_color=COLOR["muted"], opacity=0.45,
                hovertemplate="%{y}<br>Budgeted: $%{x:,.0f}<extra></extra>",
            ))
            fig_bva.add_trace(go.Bar(
                x=within["actual_amount"], y=within["category_name"], orientation="h",
                name="Actual (within budget)", marker_color=COLOR["good"],
                hovertemplate="%{y}<br>Actual: $%{x:,.0f}<extra></extra>",
            ))
            fig_bva.add_trace(go.Bar(
                x=over["actual_amount"], y=over["category_name"], orientation="h",
                name="Actual (over budget)", marker_color=COLOR["critical"],
                hovertemplate="%{y}<br>Actual: $%{x:,.0f}<extra></extra>",
            ))
            fig_bva.update_layout(
                barmode="group", xaxis_title="Amount ($)", yaxis_title="",
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0, font=dict(size=11)),
            )
            base_layout(fig_bva, height=max(300, 42 * len(bva)))
            st.plotly_chart(fig_bva, use_container_width=True, config={"displayModeBar": False})

            if not over.empty:
                names = ", ".join(over["category_name"])
                st.warning(f"⚠️ Over budget in {range_label}: {names}")
        else:
            st.info("No budgets set for the selected date range.")

    # --- Recurring & subscriptions --------------------------------------------
    st.subheader("\U0001F501 Recurring & Subscriptions")
    with st.container(border=True):
        if not recurring.empty:
            rec = recurring.copy()
            rec["amount_changed"] = (
                (rec["typical_amount"] > 0)
                & ((rec["last_amount"] - rec["typical_amount"]).abs() / rec["typical_amount"] > 0.05)
            )
            display = rec.rename(columns={
                "merchant_name": "Merchant",
                "typical_amount": "Typical Amount",
                "last_amount": "Last Amount",
                "last_txn_date": "Last Charged",
                "occurrence_count": "Charges Seen",
            })
            display["Changed?"] = display["amount_changed"].map(lambda v: "⚠️ Changed" if v else "—")
            st.dataframe(
                display[["Merchant", "Typical Amount", "Last Amount", "Last Charged", "Charges Seen", "Changed?"]]
                    .style.format({"Typical Amount": "${:,.2f}", "Last Amount": "${:,.2f}"}),
                width="stretch",
            )
            changed = rec[rec["amount_changed"]]
            if not changed.empty:
                names = ", ".join(changed["merchant_name"])
                st.warning(f"⚠️ Charge amount changed recently for: {names}")
        else:
            st.info("No recurring transactions detected yet.")

    # --- Anomalies -----------------------------------------------------------
    st.subheader("\U0001F6A9 Flagged Transactions (Isolation Forest)")
    if not anomalies.empty:
        st.dataframe(
            anomalies.style.format({"amount": "${:,.2f}", "anomaly_score": "{:.2f}"}),
            width="stretch",
        )
        st.download_button(
            "⬇ Download flagged transactions (CSV)",
            data=anomalies.to_csv(index=False).encode("utf-8"),
            file_name=f"cashpulse_flagged_transactions_{_slug(account_name)}.csv",
            mime="text/csv",
            key="download_anomalies",
        )
    else:
        st.info("No anomalies flagged yet.")

    # --- Manage transactions --------------------------------------------------
    # See _get_write_conn()'s docstring for why this is SQLite-tier-only.
    st.subheader("✏️ Manage Transactions")
    if BACKEND != "sqlite":
        st.info("Manual entry/editing is available on the local SQLite tier only. "
                 "The cloud tier's dbt pipeline rebuilds `analytics.*` from `raw.*` "
                 "on every run, so a direct write here would just be overwritten "
                 "on the next run -- see ROADMAP.md.")
    else:
        categories_df = load_table("categories")
        merchants_df = load_table("merchants")
        category_by_id = dict(zip(categories_df["category_id"], categories_df["category_name"]))
        category_names = categories_df["category_name"].tolist()
        merchant_names = merchants_df["merchant_name"].tolist()
        merchant_default_cat = dict(zip(merchants_df["merchant_name"], merchants_df["default_category_id"]))

        add_tab, edit_tab, rules_tab = st.tabs(
            ["➕ Add transaction", "\U0001F5C2️ Edit / delete", "\U0001F3f7️ Category rules"]
        )

        # --- Add ---------------------------------------------------------
        with add_tab:
            c1, c2, c3 = st.columns(3)
            with c1:
                new_date = st.date_input("Date", value=datetime.today(), key="new_txn_date")
                new_type = st.selectbox("Type", ["debit", "credit"], key="new_txn_type")
            with c2:
                new_amount = st.number_input(
                    "Amount ($)", min_value=0.01, step=1.0, format="%.2f", key="new_txn_amount"
                )
                merchant_choice = st.selectbox(
                    "Merchant", ["(none)"] + sorted(merchant_names) + ["+ Add new merchant"],
                    key="new_txn_merchant",
                )
            new_merchant_name = None
            if merchant_choice == "+ Add new merchant":
                new_merchant_name = st.text_input("New merchant name", key="new_txn_new_merchant")

            # Auto-categorization, part 1: suggest (never silently force) a
            # category the moment a known merchant is picked.
            suggested_category = None
            if merchant_choice not in ("(none)", "+ Add new merchant"):
                suggested_category = category_by_id.get(merchant_default_cat.get(merchant_choice))

            # A selectbox's `index=` argument is only honored the very first
            # time a widget with that `key` is created -- on every later
            # rerun Streamlit keeps whatever's already in session_state for
            # that key and silently ignores `index=`. So changing merchants
            # and expecting the category dropdown to visually follow needs
            # an explicit session_state write *before* the widget is
            # instantiated, guarded so it only fires when the merchant
            # selection itself just changed -- otherwise it would stomp on
            # a manual category override every time an unrelated widget
            # (e.g. the description field) triggers a rerun.
            if st.session_state.get("_new_txn_category_synced_for") != merchant_choice:
                if suggested_category:
                    st.session_state["new_txn_category"] = suggested_category
                st.session_state["_new_txn_category_synced_for"] = merchant_choice

            with c3:
                new_category = st.selectbox("Category", category_names, key="new_txn_category")
                new_recurring = st.checkbox("Recurring", key="new_txn_recurring")

            new_description = st.text_input("Description (optional)", key="new_txn_description")

            if suggested_category:
                st.caption(f"ℹ️ Auto-suggested **{suggested_category}** from this "
                            "merchant's history -- change it above if this one's different.")
            elif merchant_choice == "+ Add new merchant" and new_merchant_name:
                st.caption("New merchant -- the category you pick above will be remembered "
                            "as its default from now on (auto-categorization, part 2).")

            if st.button("Add transaction", type="primary", key="add_txn_submit"):
                merchant_to_use = (
                    _clean_text(new_merchant_name) if merchant_choice == "+ Add new merchant"
                    else (merchant_choice if merchant_choice != "(none)" else None)
                )
                if merchant_choice == "+ Add new merchant" and not merchant_to_use:
                    st.error("Enter a name for the new merchant, or choose an existing one.")
                else:
                    conn = _get_write_conn()
                    try:
                        category_id = int(
                            categories_df.loc[categories_df["category_name"] == new_category, "category_id"].iloc[0]
                        )
                        merchant_id = (
                            _get_or_create_merchant(conn, merchant_to_use, category_id)
                            if merchant_to_use else None
                        )
                        conn.execute(
                            """INSERT INTO transactions
                               (account_id, merchant_id, category_id, txn_date, amount,
                                txn_type, description, is_recurring)
                               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                            (account_id, merchant_id, category_id, new_date.isoformat(),
                             round(abs(float(new_amount)), 2), new_type,
                             _clean_text(new_description), int(new_recurring)),
                        )
                        conn.commit()
                        st.success(f"Added {new_type} of ${new_amount:,.2f} on {new_date.isoformat()}.")
                        _invalidate_and_rerun()
                    finally:
                        conn.close()

        # --- Edit / delete -------------------------------------------------
        with edit_tab:
            all_txns = load_table("all_transactions", {"account_id": account_id})
            if all_txns.empty:
                st.info("No transactions yet for this account.")
            else:
                display_txns = all_txns.rename(columns={
                    "txn_date": "Date", "merchant_name": "Merchant", "category_name": "Category",
                    "amount": "Amount", "txn_type": "Type", "description": "Description",
                    "is_recurring": "Recurring",
                }).set_index("transaction_id")
                display_txns["Date"] = pd.to_datetime(display_txns["Date"]).dt.date
                display_txns["Recurring"] = display_txns["Recurring"].astype(bool)
                display_txns["Delete?"] = False

                st.caption(f"Showing the {len(display_txns):,} most recent transactions for "
                            "this account. Edit a cell, or check “Delete?”, then save.")
                edited = st.data_editor(
                    display_txns,
                    column_config={
                        "Category": st.column_config.SelectboxColumn(options=category_names, required=True),
                        "Type": st.column_config.SelectboxColumn(options=["debit", "credit"], required=True),
                        "Amount": st.column_config.NumberColumn(format="$%.2f", min_value=0.01),
                        "Date": st.column_config.DateColumn(format="YYYY-MM-DD", required=True),
                        "Delete?": st.column_config.CheckboxColumn(
                            help="Check, then Save changes, to permanently delete this row."
                        ),
                    },
                    num_rows="fixed",
                    width="stretch",
                    key="edit_txn_editor",
                )
                if st.button("\U0001F4be Save changes", key="save_txn_edits"):
                    conn = _get_write_conn()
                    try:
                        n_deleted = n_updated = 0
                        for txn_id, row in edited.iterrows():
                            if row["Delete?"]:
                                conn.execute(
                                    "DELETE FROM transactions WHERE transaction_id = ?", (int(txn_id),)
                                )
                                n_deleted += 1
                                continue
                            category_id = int(
                                categories_df.loc[categories_df["category_name"] == row["Category"], "category_id"].iloc[0]
                            )
                            merchant_name = _clean_text(row["Merchant"])
                            merchant_id = (
                                _get_or_create_merchant(conn, merchant_name, category_id)
                                if merchant_name else None
                            )
                            conn.execute(
                                """UPDATE transactions
                                   SET txn_date = ?, merchant_id = ?, category_id = ?, amount = ?,
                                       txn_type = ?, description = ?, is_recurring = ?
                                   WHERE transaction_id = ?""",
                                (pd.Timestamp(row["Date"]).strftime("%Y-%m-%d"), merchant_id, category_id,
                                 round(abs(float(row["Amount"])), 2), row["Type"],
                                 _clean_text(row["Description"]), int(bool(row["Recurring"])), int(txn_id)),
                            )
                            n_updated += 1
                        conn.commit()
                        st.success(f"Saved: {n_updated} updated, {n_deleted} deleted.")
                        _invalidate_and_rerun()
                    finally:
                        conn.close()

        # --- Category rules --------------------------------------------------
        with rules_tab:
            st.caption("Each merchant's default category -- the suggestion shown on the "
                        "Add tab when you pick that merchant. Editing it here only changes "
                        "the suggestion going forward, not any past transactions.")
            rules_df = merchants_df.copy()
            rules_df["Default Category"] = rules_df["default_category_id"].map(category_by_id)
            rules_df = rules_df.rename(columns={"merchant_name": "Merchant"})
            rules_df = rules_df.set_index("merchant_id")[["Merchant", "Default Category"]]
            edited_rules = st.data_editor(
                rules_df,
                column_config={
                    "Merchant": st.column_config.TextColumn(disabled=True),
                    "Default Category": st.column_config.SelectboxColumn(
                        options=category_names, required=True
                    ),
                },
                num_rows="fixed",
                width="stretch",
                key="rules_editor",
            )
            if st.button("\U0001F4be Save category rules", key="save_rules"):
                conn = _get_write_conn()
                try:
                    n = 0
                    for merchant_id, row in edited_rules.iterrows():
                        new_cat_id = int(
                            categories_df.loc[categories_df["category_name"] == row["Default Category"], "category_id"].iloc[0]
                        )
                        conn.execute(
                            "UPDATE merchants SET default_category_id = ? WHERE merchant_id = ?",
                            (new_cat_id, int(merchant_id)),
                        )
                        n += 1
                    conn.commit()
                    st.success(f"Updated {n} merchant categor{'y' if n == 1 else 'ies'}.")
                    _invalidate_and_rerun()
                finally:
                    conn.close()

    render_integrations()


if __name__ == "__main__":
    main()
